spring:
  application:
    name: boost
  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: dev

  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0.7
          max-tokens: 500
    retry:
      backoff:
        initial-interval: 1s
        multiplier: 2
      max-attempts: 5


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true

jwt:
  access-token-expire-time: 30m
  refresh-token-expire-time: 7d

boost:
  aws:
    upload:
      expire-seconds: 900
  file:
    max-upload-size: 5MB
ai:
  comment:
    transform:
      timeout-seconds: 10

boosting-score:
  task:
    todo: 1
    progress: 2
    review: 3
    done: 5
  comment-score: 1
  approve-score: 3

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
        info: actuator/info
        metrics: actuator/metrics
